"""Add completed field to goals

Revision ID: 3a41742d79d0
Revises: 
Create Date: 2025-02-08 13:04:46.675768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a41742d79d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'budgets', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'chat_history', 'users', ['user_id'], ['id'])
    op.add_column('goals', sa.Column('completed', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'goals', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'recurring_expenses', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'recurring_expenses', type_='foreignkey')
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_column('goals', 'completed')
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    # ### end Alembic commands ###
